services:
  db:
    image: postgres:17 # Use the official PostgreSQL image
    restart: always # Restart the container if it stops
    container_name: postgres
    shm_size: '128mb'
    ports:
      - "${HOST_PORT}:5432"
    environment:
      DB_HOST: ${DB_HOST} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    env_file: .env
    build:
      context: backend 
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data: